---
- hosts: all
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - httpd
        - wget
        - java
        - xyz
        - abc
      tags:
        - install_packages
